# Generated by Django 3.2.25 on 2024-11-04 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Tipo de Pet')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Foto')),
                ('location', models.CharField(max_length=100, verbose_name='Localização')),
                ('interests', models.CharField(max_length=200, verbose_name='Interesses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Tipo de Pet Preferido')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça Preferida')),
                ('age_min', models.IntegerField(verbose_name='Idade Mínima')),
                ('age_max', models.IntegerField(verbose_name='Idade Máxima')),
                ('interests', models.CharField(max_length=200, verbose_name='Interesses')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
