# Generated by Django 3.2.25 on 2024-11-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='breed',
        ),
    ]
